# Generated by Django 5.0.4 on 2024-05-12 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cartitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
